# Generated by Django 5.2.7 on 2025-10-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(help_text='MyAnimeList ID', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='anime_posters/')),
                ('poster_api_url', models.URLField(blank=True, max_length=500, null=True)),
                ('trailer_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
