# Generated by Django 5.2.7 on 2025-10-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['title'], 'verbose_name_plural': 'Anime'},
        ),
        migrations.AddField(
            model_name='anime',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
