# Generated by Django 5.2.7 on 2025-10-05 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_options_anime_download_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeWatchLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Server F1, Dub, Sub', max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_links', to='anime.anime')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
