# Generated by Django 5.2.7 on 2025-10-04 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0002_tvseries_download_link_tvseries_watch_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_episodes', to='tvseries.tvseries'),
        ),
    ]
