# Generated by Django 5.2.7 on 2025-10-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0003_episode_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvseries',
            name='start_date',
        ),
        migrations.AddField(
            model_name='tvseries',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date'),
        ),
    ]
