# Generated by Django 5.2.7 on 2025-10-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_download_link_movie_watch_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, help_text='IMDb ID (e.g., tt1375666)', max_length=20, null=True, unique=True),
        ),
    ]
