# Generated by Django 5.2.7 on 2025-10-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_options_remove_movie_cast_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_api_url',
            field=models.URLField(blank=True, help_text='URL for the poster from OMDb API', max_length=500, null=True),
        ),
    ]
